[env:esp32nodemcu]
platform = espressif32
board = nodemcu-32s
framework = arduino

; --- Velocidades de Comunicación ---
monitor_speed = 115200
upload_speed = 921600 ; El ESP32 soporta velocidades de carga más altas que el 8266

; --- Puertos (Asegúrate que siga siendo COM7 en tu PC) ---
monitor_port = COM1
upload_port = COM1

; --- Configuración del Sistema de Archivos ---
board_build.filesystem = littlefs 

; --- Banderas de Compilación ---
build_flags = 
    -D MQTT_MAX_PACKET_SIZE=512
    -D CORE_DEBUG_LEVEL=0

; --- Librerías (Adaptadas para ESP32) ---
lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.18.5
    https://github.com/io7lab/IO7F32.git
    adafruit/Adafruit MAX31865 library @ ^1.6.2
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    adafruit/Adafruit BusIO @ ^1.14.1
    Wire

