[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

# Recuerda verificar si el puerto COM cambia al conectar la nueva placa
# Nota: Esto solo afecta si subes por cable USB. Para OTA por GitHub no importa el COM.
upload_port = COM1
monitor_port = COM1

build_flags = 
    -D MQTT_MAX_PACKET_SIZE=512

lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.18.5
    https://github.com/io7lab/IO7F32.git