[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino

monitor_speed = 115200
upload_speed = 921600 

; Reemplaza COM1 por el puerto real de tu placa (ej. COM3, COM4, COM5)
monitor_port = COM7
upload_port = COM7

board_build.filesystem = littlefs 

build_flags = 
    -D MQTT_MAX_PACKET_SIZE=1024  ; Aumentado para buffers MQTT grandes
    -D CORE_DEBUG_LEVEL=0

lib_deps = 
    SPI
    Wire
    bblanchon/ArduinoJson @ ^6.21.3
    plerup/EspSoftwareSerial @ ^8.1.0
    4-20ma/ModbusMaster @ ^2.0.1
    io7lab/IO7F8266@^0.1.1